---
Attribute:
  enabled: false
  exclude: []
BooleanParameter:
  enabled: true
  exclude:
  - respond_to_missing?
ClassVariable:
  enabled: true
  exclude: []
ControlParameter:
  enabled: false
  exclude: []
DataClump:
  enabled: true
  exclude: []
  max_copies: 2
  min_clump_size: 2
DuplicateMethodCall:
  enabled: true
  exclude:
  - Guacamole::DocumentModelMapper#document_to_model
  - Guacamole::DocumentModelMapper#model_to_document
  - Guacamole::Configuration#_add_missing_methods_to_database
  max_calls: 1
  allow_calls: []
FeatureEnvy:
  enabled: false
  exclude: []
IrresponsibleModule:
  enabled: true
  exclude:
  - - !ruby/regexp /Generators/
LongParameterList:
  enabled: true
  exclude: []
  max_params: 2
  overrides:
    initialize:
      max_params: 3
LongYieldList:
  enabled: true
  exclude: []
  max_params: 2
NestedIterators:
  enabled: true
  exclude:
  - Guacamole::Configuration#_add_missing_methods_to_database
  max_allowed_nesting: 2
  ignore_iterators: []
NilCheck:
  enabled: true
  exclude: []
RepeatedConditional:
  enabled: true
  exclude: []
  max_ifs: 2
TooManyInstanceVariables:
  enabled: true
  exclude:
  - Guacamole::DocumentModelMapper
  max_instance_variables: 3
TooManyMethods:
  enabled: true
  exclude: []
  max_methods: 20
TooManyStatements:
  enabled: true
  exclude:
  - each
  - Guacamole::DocumentModelMapper#document_to_model
  - Guacamole::DocumentModelMapper#model_to_document
  - Guacamole::Collection::ClassMethods#create_document_from
  - Guacamole::Collection::ClassMethods#create_referenced_by_models_of
  - Guacamole::Configuration#_add_missing_methods_to_database
  - Guacamole::Configuration#create_database_connection_from
  max_statements: 5
UncommunicativeMethodName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^[a-z]$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept: []
UncommunicativeModuleName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  accept: []
UncommunicativeParameterName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept: []
UncommunicativeVariableName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept: []
UnusedParameters:
  enabled: true
  exclude:
  - Guacamole::Model#==
UtilityFunction:
  enabled: false
  exclude: []
  max_helper_calls: 0
